### ISSUE TITLE
Add .NET Framework 4.6 target to NuGet package

### ISSUE THREAD

**Issue by william-gross** [GregSmalter/TEWL#2]
After referencing TEWL from EWL and trying to build, I receive warnings related to binding-redirect conflicts for System.Net.Http. I have seen this before when referencing other NuGet packages that only target .NET Standard. EWL still targets .NET 4.6.2, and while in theory there should be no problem referencing .NET Standard, it seems to be a bit bumpy in practice.

You can fix this easily by adding an additional target for .NET Framework 4.6. Many packages already do this; see https://www.nuget.org/packages/ClosedXML for an example.

**Comment by samrueby** [comment]
I agree that this is recommended practice. https://twitter.com/terrajobst/status/1108881246757675008

**Comment by samrueby** [comment]
Though they overwhelmingly seem to suggest 4.6.1 rather than 4.6. I would recommend targeting 4.6.1. http://netstandard-targets.stephencleary.com/

**Comment by GregSmalter** [comment]
This is done. Had to use .net pack to achieve this.
